### ISSUE TITLE
Design Issue: Improve Button Spacing and Responsiveness

### ISSUE THREAD

**Issue by AllysaAirish** [izel26/QUIZ-APP-1#6]
1. Current Behavior:  
   - Buttons have fixed `margin: 10px 5px` and `padding: 10px 20px`, which works on medium screens but may look cramped or misaligned on smaller screens.  
   - The button styles (e.g., `font-size`) might not adapt for responsiveness due to missing media queries.  

2. Expected Behavior:  
   - Buttons should have uniform and flexible spacing to ensure proper alignment.  
   - They should resize or adjust spacing gracefully on smaller devices for better usability and aesthetics.  

3. Suggestions for Improvement:  
   - Add a container class for the buttons and use `flexbox` to ensure proper alignment:  
     ```css
     .button-container {
         display: flex;
         justify-content: center;
         flex-wrap: wrap;
         gap: 10px;
     }
     ```
   - Set up responsive padding and font-size adjustments using media queries:  
     ```css
     button {
         margin: 5px;
         padding: 12px 24px;
         font-size: 16px;
     }

     @media (max-width: 500px) {
         button {
             width: 100%;
             margin: 5px 0;
             font-size: 14px;
         }
     }
     ```
   - Use `gap` in `flexbox` instead of individual `margin` for consistent spacing.  

4. Attachments:  
   - A mockup or wireframe of the intended button layout (if available).
